export default {
  UPDATE_CHART_TITLE: 'UPDATE_CHART_TITLE',
  UPDATE_SCALE: 'UPDATE_SCALE',
  UPDATE_CANVAS_WIDTH: 'UPDATE_CANVAS_WIDTH',
  UPDATE_CANVAS_HEIGHT: 'UPDATE_CANVAS_HEIGHT',
  UPDATE_BACKGROUND_COLOR: 'UPDATE_BACKGROUND_COLOR',
  UPDATE_CHART_LIST: 'UPDATE_CHART_LIST'
};
